(use gl)
(use gl.glut)

(define (display-pos-axis x y z)
  (gl-color 1 0 0 1)
  (gl-push-matrix)
  (gl-begin GL_LINES)
  (gl-vertex x y z)
  (gl-vertex (+ x 1) y z)
  (gl-color 0 1 0 1)
  (gl-vertex x y z)
  (gl-vertex x (+ y 1) z)
  (gl-color 0 0 1 1)
  (gl-vertex x y z)
  (gl-vertex x y (+ 1 z))
  (gl-end)
  (gl-pop-matrix)
  )
