(use gl)
(use gl.glut)

(define *width* 640)
(define *height* 640)
(define *light0-pos* #f32(0 5 0 1))
(define *light0-color* #f32(1 1 1 1))

(define (display)
  (gl-clear (logior GL_COLOR_BUFFER_BIT GL_DEPTH_BUFFER_BIT))
  (gl-rotate 1 0 1 0)
  (gl-light GL_LIGHT0 GL_POSITION *light0-pos*)
  (gl-material GL_FRONT_AND_BACK GL_DIFFUSE #f32(0 0 1 1))
  (glut-solid-cube 1)
  (glut-swap-buffers)
  )

(define (init)
  (gl-clear-color 1.0 1.0 1.0 1.0)
  (gl-enable GL_DEPTH_TEST)
  (gl-enable GL_LIGHTING)
  (gl-enable GL_LIGHT0)
  (gl-light GL_LIGHT0 GL_DIFFUSE *light0-color*)
  (gl-light GL_LIGHT0 GL_SPECULAR *light0-color*)
  (gl-enable GL_CULL_FACE)
  (gl-cull-face GL_BACK)
  )

(define (keyboard key x y)
  (cond ( (= key (char->integer #\q)) (exit 0) )
        ( (= key (char->integer #\a)) (glut-post-redisplay) )
        ))

(define (idle)
  (glut-post-redisplay))

(define (resize w h)
  (gl-viewport 0 0 w h)
  (gl-load-identity)
  (gl-translate 0 0 -0.01)
  (glu-perspective 30 (/ w h) 1 100)
  (glu-look-at 3 4 5 0 0 0 0 1 0)
  )

(define (main args)
  (glut-init args)
  (glut-init-window-size *width* *height*)
  (glut-init-display-mode (logior GLUT_RGBA GLUT_DOUBLE GLUT_DEPTH))
  (glut-create-window "Colour")
  (glut-display-func display)
  (glut-reshape-func resize)
  (glut-keyboard-func keyboard)
  (glut-idle-func idle)
  (init)
  (glut-main-loop))
